# Generated by Django 4.0.2 on 2022-02-04 16:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='USERID')),
                ('name', models.CharField(max_length=10, verbose_name='NAME')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('gold', models.IntegerField(verbose_name='GOLD')),
                ('level', models.IntegerField(verbose_name='LEVEL')),
                ('inventory', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
            ],
        ),
    ]
