# Generated by Django 4.0.2 on 2022-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=10, unique=True, verbose_name="USERID"),
        ),
    ]
